title: Murilo Camargos # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: 'Data Scientist at <a href="https://emap.fgv.br/" target="_blank">FGV (AMAp)</a>'
theme: jekyll-theme-minimal
google_analytics: UA-180218021-1 # your Google Analytics tracking ID here