title: Murilo Camargos # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: 'Ph.D. Candidate investigating data-driven incremental learning techniques at <a href="ppgee.ufmg.br/" target="_blank">UFMG</a>'
theme: jekyll-theme-minimal
google_analytics: UA-180218021-1 # your Google Analytics tracking ID here